#!/usr/bin/env bash
set -euo pipefail

RONDE_ROOT="$(git rev-parse --show-toplevel)"
RONDE_INVENTORY="$RONDE_ROOT/docs/context/generated/repository-inventory.md"
RONDE_LEDGER="$RONDE_ROOT/docs/context/history/commit-ledger.md"
RONDE_INVENTORY_TMP="$(mktemp)"
RONDE_LEDGER_TMP="$(mktemp)"

cleanup() {
  rm -f "$RONDE_INVENTORY_TMP" "$RONDE_LEDGER_TMP"
}
trap cleanup EXIT

cd "$RONDE_ROOT"

count_files() {
  local pattern="$1"
  find . -path './.git' -prune -o -path './.claude' -prune -o -type f -name "$pattern" -print | wc -l | tr -d ' '
}

RONDE_SOURCE_COMMIT="$(git rev-parse HEAD)"
RONDE_SOURCE_DATE="$(git show -s --format=%cs HEAD)"
RONDE_COMMIT_COUNT="$(git rev-list --count HEAD)"
RONDE_REMOTE="$(git remote get-url origin 2>/dev/null || printf 'not configured')"
RONDE_DIRTY_COUNT="$(git status --porcelain | wc -l | tr -d ' ')"

{
  printf '# Generated Repository Inventory\n\n'
  printf '> Mechanical index generated by `scripts/update-context-library.sh`. Do not hand-edit.\n\n'
  printf '## Repository baseline\n\n'
  printf -- '- Source commit: `%s`\n' "$RONDE_SOURCE_COMMIT"
  printf -- '- Source commit date: %s\n' "$RONDE_SOURCE_DATE"
  printf -- '- Commit count: %s\n' "$RONDE_COMMIT_COUNT"
  printf -- '- Working-tree entries when generated: %s\n' "$RONDE_DIRTY_COUNT"
  printf -- '- Origin: `%s`\n\n' "$RONDE_REMOTE"
  printf '## File composition\n\n'
  printf '| Type | Count |\n| --- | ---: |\n'
  printf '| Swift | %s |\n' "$(count_files '*.swift')"
  printf '| XCTest files | %s |\n' "$(find . -type f -name '*Tests.swift' -print | wc -l | tr -d ' ')"
  printf '| Markdown | %s |\n' "$(count_files '*.md')"
  printf '| JSON resources | %s |\n\n' "$(count_files '*.json')"
  printf '## Source areas\n\n'
  find 'Ronde Watch App' -mindepth 1 -maxdepth 1 -type d -print | sort | sed 's#^#- `#; s#$#`#'
  printf '\n## Canonical context\n\n'
  printf -- '- `AGENTS.md`\n- `PROJECT.md`\n- `docs/product-contract.md`\n- `docs/context/CURRENT_STATE.md`\n- `docs/context/ARCHITECTURE.md`\n- `docs/context/ROADMAP.md`\n- `docs/context/OPERATIONS.md`\n- `docs/context/CHANGELOG.md`\n'
} > "$RONDE_INVENTORY_TMP"

{
  printf '# Complete Git Commit Ledger\n\n'
  printf '> Generated from Git. Git remains authoritative. Context-only refresh commits are excluded.\n\n'
  printf -- '- Source commit: `%s`\n' "$RONDE_SOURCE_COMMIT"
  printf -- '- Source commit date: %s\n' "$RONDE_SOURCE_DATE"
  printf -- '- Tracked commit count: %s\n\n' "$RONDE_COMMIT_COUNT"
  printf '| Date | Commit | Subject |\n| --- | --- | --- |\n'
  git log --reverse --date=short --pretty=format:'%ad%x09%h%x09%s' |
  while IFS=$'\t' read -r commit_date commit_sha commit_subject || [[ -n "${commit_date:-}" ]]; do
    [[ "$commit_subject" == 'chore(context): refresh generated library' ]] && continue
    commit_subject="${commit_subject//|/\\|}"
    printf '| %s | `%s` | %s |\n' "$commit_date" "$commit_sha" "$commit_subject"
  done
} > "$RONDE_LEDGER_TMP"

mv "$RONDE_INVENTORY_TMP" "$RONDE_INVENTORY"
mv "$RONDE_LEDGER_TMP" "$RONDE_LEDGER"
trap - EXIT

printf 'Updated Ronde context library.\n'
